### ISSUE TITLE
npm install breaks with this message: "Error: ref-napi@1.4.1 install: `node-gyp rebuild`"

### ISSUE THREAD

**Issue by ZiadJ** [rucken/core-nestjs#177]
![image](https://user-images.githubusercontent.com/1817207/61992391-bf118b80-b06e-11e9-8b8f-1a5317d3526c.png)
Does anyone know what I can do out of this? I've updated NodeJs to v12.7.0 and Python to the latest version as well but that didn't help.

**Comment by ZiadJ** [comment]
I tried to go for the server side code instead on github.com/rucken/core and got this error this time: 
![image](https://user-images.githubusercontent.com/1817207/61992618-e4ec5f80-b071-11e9-83d3-6417c7652c77.png)

I guess my machine does not know how to run .sh files which in turn is causing the error in the other installation.

**Comment by ZiadJ** [comment]
Nevermind, I was running it from a PowerShell terminal. Using a Bash terminal will probably fix it so I'll close this issue once I can confirm it.

**Comment by ZiadJ** [comment]
The build did run on the Core project but I'm still getting those errors with the core-nestjs project: 
![image](https://user-images.githubusercontent.com/1817207/61993226-b5d9ec00-b079-11e9-9fc3-43a615566aa1.png)

Any ideas anyone?

**Comment by EndyKaufman** [comment]
Current versions and all changes tested only one platform - linux
all release force run build on CI: 
linux - https://travis-ci.org/rucken/core-nestjs ![Build Status][travis-image]
windows - https://ci.appveyor.com/project/EndyKaufman/core-nestjs/branch/master ![Appveyor CI](https://ci.appveyor.com/api/projects/status/sda540c6vpj47cx7/branch/master?svg=true)


[travis-image]: https://travis-ci.org/rucken/core-nestjs.svg?branch=master
[travis-url]: https://travis-ci.org/rucken/core-nestjs

**Comment by ZiadJ** [comment]
I tried running `node-gyp rebuild` separately and it dies with those messages: 
![image](https://user-images.githubusercontent.com/1817207/62002006-eae34e80-b10c-11e9-92dd-32ad1cbc41ae.png)
![image](https://user-images.githubusercontent.com/1817207/62002014-1403df00-b10d-11e9-8b27-0feb3993c678.png)
I'm running from the bash terminal with the latest versions of Python and NodeJs installed. I also run `npm install --global --production windows-build-tools` as recommended their npm page but I'm not sure what else I might have missed. 

The [core ](https://github.com/rucken/core)project runs just fine though so hopefully things run fine here too once I can get over the node-gyp building process.

**Comment by ZiadJ** [comment]
> 
> 
> Current versions and all changes tested only one platform - linux
> all release force run build on CI:
> linux - https://travis-ci.org/rucken/core-nestjs ![Build Status](https://camo.githubusercontent.com/2bacb70e677806cacfe1fdf6be3d949ef819656f/68747470733a2f2f7472617669732d63692e6f72672f7275636b656e2f636f72652d6e6573746a732e7376673f6272616e63683d6d6173746572)
> windows - https://ci.appveyor.com/project/EndyKaufman/core-nestjs/branch/master ![Appveyor CI](https://camo.githubusercontent.com/a59da12bd0cafd8e42ff877abecd350e45098255/68747470733a2f2f63692e6170707665796f722e636f6d2f6170692f70726f6a656374732f7374617475732f736461353430633676706a34376378372f6272616e63682f6d61737465723f7376673d74727565)

Can we hope for a successful Windows build any time soon?

**Comment by ZiadJ** [comment]
@EndyKaufman If the failing part of the build is not not an essential part would commenting it in the build script help? I don't mind running it with a few missing components for now if it's going to be fixed at a later point.

**Comment by ZiadJ** [comment]
To be clear the main concern is that the project I'm aiming at will make heavy reliance on volunteers so the limitation will end up reducing the size of the audience and thus it's ability to progress.

**Comment by EndyKaufman** [comment]
@ZiadJ please remove all installed python and nodejs from windows, next run ccleaner and remove unused registry keys and other trash files, after it reboot pc

download latest nodejs and install it, read all install steps, search check box or other control for install external utils, if found it, mark it

after install reboot pc
```
git clone https://github.com/rucken/core-nestjs.git
cd core-nestjs
npm i
npm run build
npm run start:dev
```

I'll try to do it all tomorrow

**Comment by EndyKaufman** [comment]
after update scripts for build, build on windows is **OK** https://ci.appveyor.com/project/EndyKaufman/core-nestjs/builds/26360538

and i tested https://github.com/rucken/core-nestjs#usage in clear virtual machine with windows is **OK**

_please try remove all installed python, nodejs and microsoft visual redistributable
and install nodejs and mark externals utils on install step_

**after, read and do https://github.com/rucken/core-nestjs#usage**
